fun_facts = [
    "Honey never spoils and can last for thousands of years.",
    "A group of flamingos is called a 'flamboyance.'",
    "Octopuses have three hearts.",
    "Bananas are berries, but strawberries are not.",
    "There are more stars in the universe than grains of sand on Earth.",
    "The inventor of the Pringles can is buried in one.",
    "Wombat poop is cube-shaped.",
    "Sharks existed before trees.",
    "Cows have best friends and get stressed when separated.",
    "Sloths can hold their breath longer than dolphins.",
    "A blue whale's heart is the size of a small car.",
    "The Eiffel Tower can grow taller in summer.",
    "Peanuts are not nuts; they are legumes.",
    "A day on Venus is longer than a year on Venus.",
    "Butterflies can taste with their feet.",
    "The dot over the letter 'i' is called a tittle.",
    "A cloud can weigh over a million pounds.",
    "Pineapples take about two years to grow.",
    "Otters hold hands while sleeping to stay together.",
    "The shortest war in history lasted 38 minutes.",
    "Giraffes have the same number of neck vertebrae as humans.",
    "Scotland’s national animal is the unicorn.",
    "The heart of a shrimp is located in its head.",
    "The world's largest desert is Antarctica.",
    "Apples float because they are 25% air.",
    "Cats can’t taste sweetness.",
    "A bolt of lightning is five times hotter than the sun.",
    "Humans share about 60% of their DNA with bananas.",
    "Koalas have fingerprints similar to humans.",
    "There are more fake flamingos in the world than real ones.",
    "A jiffy is an actual unit of time: 1/100th of a second.",
    "There are 293 ways to make change for a dollar.",
    "The longest hiccuping spree lasted 68 years.",
    "Some penguins propose to their mates with a pebble.",
    "You can't hum while holding your nose closed.",
    "Sea otters have a pouch in their skin to store their favorite rocks.",
    "An octopus has nine brains.",
    "A snail can sleep for three years.",
    "Water can boil and freeze at the same time.",
    "Hot water freezes faster than cold water, known as the Mpemba effect.",
    "The wood frog can survive being frozen solid.",
    "Humans are the only animals that blush.",
    "Cows produce more milk when they listen to relaxing music.",
    "A baby octopus is the size of a flea at birth.",
    "The moon has moonquakes.",
    "A day on Mercury lasts 1,408 hours.",
    "A cockroach can live for weeks without its head.",
    "Polar bears have black skin under their white fur.",
    "Elephants can 'hear' with their feet.",
    "The human nose can detect over a trillion smells.",
    "Spiders can regrow lost legs.",
    "Goats have accents.",
    "The inventor of the frisbee was turned into a frisbee after he died.",
    "A crocodile can’t stick out its tongue.",
    "Sharks don’t have bones.",
    "Sloths can turn their heads almost 360 degrees.",
    "An ant can lift 50 times its body weight.",
    "The original name for a butterfly was 'flutterby.'",
    "Humans have more bacteria in their mouths than there are people on Earth.",
    "A rhinoceros' horn is made of hair.",
    "Starfish don’t have brains.",
    "Jellyfish are 95% water.",
    "A group of hedgehogs is called a prickle.",
    "The inventor of the Rubik’s Cube couldn’t solve it for a month.",
    "Tomatoes have more genes than humans.",
    "A newborn kangaroo is the size of a jellybean.",
    "Tigers have striped skin, not just striped fur.",
    "Sharks are older than dinosaurs.",
    "A group of crows is called a murder.",
    "Dogs can smell your feelings.",
    "The tongue of a blue whale weighs as much as an elephant.",
    "There’s a species of jellyfish that can live forever.",
    "The human body contains enough carbon to fill 9,000 pencils.",
    "Cows can walk upstairs but not downstairs.",
    "Alaska is the westernmost and easternmost U.S. state.",
    "The human brain generates enough electricity to power a light bulb.",
    "Horses can’t vomit.",
    "A flea can jump 350 times its body length.",
    "Your stomach gets a new lining every three days.",
    "Snakes can sense earthquakes from 75 miles away.",
    "Humans have about 206 bones as adults but over 300 at birth.",
    "The inventor of Velcro got the idea from burrs stuck to his dog.",
    "Birds are the closest living relatives of dinosaurs.",
    "The Great Wall of China is not visible from space.",
    "Bananas grow upside down.",
    "Goldfish have a memory span of at least three months.",
    "The fingerprints of a koala are indistinguishable from a human’s.",
    "A chameleon’s tongue is twice the length of its body.",
    "Penguins can jump six feet in the air.",
    "Some turtles can breathe through their butts.",
    "The average person will spend six months of their life waiting for red lights to turn green.",
    "Pigeons can do math at a basic level.",
    "The Twitter bird has a name: Larry.",
    "An octopus's tentacles can regenerate."
]

astronomy_facts = [
    "The Sun accounts for 99.86% of the mass in the solar system.",
    "Venus is the hottest planet in the solar system, with surface temperatures over 450°C.",
    "A day on Venus is longer than a year on Venus.",
    "There are more stars in the universe than grains of sand on Earth.",
    "The Milky Way galaxy is about 100,000 light-years across.",
    "The Andromeda Galaxy is on a collision course with the Milky Way.",
    "Jupiter has 95 confirmed moons as of 2023.",
    "A neutron star is so dense that a sugar-cube-sized piece would weigh billions of tons.",
    "Black holes can 'spaghettify' objects that get too close.",
    "The Moon is slowly moving away from Earth at a rate of about 3.8 cm per year.",
    "A day on Mars is only slightly longer than a day on Earth (24 hours, 37 minutes).",
    "Saturn’s moon Titan has rivers, lakes, and seas of liquid methane.",
    "The largest volcano in the solar system, Olympus Mons, is on Mars.",
    "A light-year is the distance light travels in a year: about 5.88 trillion miles.",
    "The observable universe is about 93 billion light-years in diameter.",
    "There’s a planet called WASP-12b that’s being eaten by its parent star.",
    "Pluto was reclassified as a dwarf planet in 2006.",
    "The largest asteroid in the solar system, Ceres, is also classified as a dwarf planet.",
    "The Great Red Spot on Jupiter is a storm that’s been raging for at least 300 years.",
    "Uranus rotates on its side, with an axial tilt of 98 degrees.",
    "Neptune’s winds can reach speeds of over 1,200 mph.",
    "The Sun will eventually become a white dwarf after its red giant phase.",
    "There are rogue planets drifting through space without a star.",
    "Some stars are so massive that they end their lives as black holes.",
    "Mercury has no atmosphere to retain heat, so it experiences extreme temperature swings.",
    "The Kuiper Belt is home to icy bodies and dwarf planets like Pluto.",
    "The Oort Cloud is a theoretical shell of icy objects surrounding the solar system.",
    "Saturn’s rings are made primarily of ice and rock particles.",
    "The fastest spinning planet in the solar system is Jupiter.",
    "The Sun's core is about 15 million degrees Celsius.",
    "Comets are often referred to as 'dirty snowballs' because they contain ice, rock, and dust.",
    "A pulsar is a rapidly spinning neutron star that emits beams of radiation.",
    "The closest star system to Earth is Alpha Centauri, about 4.37 light-years away.",
    "There’s a hexagonal storm at Saturn’s north pole.",
    "The Moon has quakes called 'moonquakes,' caused by tidal stresses from Earth.",
    "Venus spins in the opposite direction to most planets.",
    "Betelgeuse, a red supergiant, is expected to explode as a supernova in the future.",
    "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.",
    "The largest moon in the solar system is Ganymede, which orbits Jupiter.",
    "There’s a giant cloud of alcohol in space near the constellation Sagittarius.",
    "The coldest place in the universe is the Boomerang Nebula, at -272°C.",
    "Mars has the largest dust storms in the solar system.",
    "A year on Neptune lasts 165 Earth years.",
    "The farthest human-made object, Voyager 1, is in interstellar space.",
    "There’s a diamond planet called 55 Cancri e.",
    "The first exoplanet was discovered in 1992 around a pulsar.",
    "Some stars can have planets in the 'habitable zone,' where liquid water might exist.",
    "Triton, Neptune's largest moon, orbits in the opposite direction of Neptune’s rotation.",
    "Earth's magnetic field protects us from solar wind and cosmic radiation.",
    "The Sun has an 11-year solar activity cycle.",
    "Jupiter’s moon Europa may have a subsurface ocean beneath its icy crust.",
    "A quasar is a supermassive black hole actively feeding on material.",
    "The largest structure in the universe is the Hercules-Corona Borealis Great Wall.",
    "Some galaxies have supermassive black holes billions of times the Sun’s mass.",
    "The Milky Way is part of a galaxy cluster called the Local Group.",
    "The Big Bang occurred about 13.8 billion years ago.",
    "Neutrinos, tiny particles, are constantly passing through your body from the Sun.",
    "The Moon has no atmosphere, which is why footprints on its surface could last millions of years.",
    "The Sun contains 74% hydrogen and 24% helium by mass.",
    "The Hubble Space Telescope has taken over 1.5 million observations.",
    "Mars has polar ice caps made of water and dry ice (frozen carbon dioxide).",
    "A black hole at the center of the Milky Way is called Sagittarius A*.",
    "Stars are born in clouds of gas and dust called nebulae.",
    "A white dwarf can explode in a supernova if it gains enough mass from a companion star.",
    "The most common type of star in the universe is the red dwarf.",
    "The Crab Nebula is the remnant of a supernova observed in 1054 AD.",
    "Halley’s Comet is visible from Earth every 76 years.",
    "Astronauts in space can grow up to 2 inches taller due to reduced gravity.",
    "Earth’s rotation is gradually slowing down, adding milliseconds to our days.",
    "Solar flares can disrupt communication and navigation systems on Earth.",
    "Asteroids are leftovers from the early solar system.",
    "The largest meteorite ever found weighs over 60 tons.",
    "There’s a star named UY Scuti, one of the largest known stars in the universe.",
    "The Sun will eventually engulf the inner planets during its red giant phase.",
    "Earth is the only planet not named after a Greek or Roman god.",
    "The James Webb Space Telescope can see farther back in time than Hubble.",
    "Saturn could float in water because it’s less dense than water.",
    "The surface of Mercury is covered in craters from asteroid impacts.",
    "The Kuiper Belt extends beyond Neptune’s orbit.",
    "A day on Uranus lasts 17 hours and 14 minutes.",
    "The largest canyon in the solar system, Valles Marineris, is on Mars.",
    "The Sun loses about 4 million tons of mass every second due to fusion.",
    "Some exoplanets are tidally locked, with one side always facing their star.",
    "The first stars in the universe were made almost entirely of hydrogen and helium.",
    "Stars twinkle because of turbulence in Earth’s atmosphere.",
    "Meteor showers occur when Earth passes through the debris of a comet.",
    "Venus has more volcanoes than any other planet in the solar system.",
    "The rotation of the Earth causes the Coriolis effect, influencing weather patterns.",
    "Earth’s core is as hot as the surface of the Sun.",
    "If two pieces of metal touch in space, they will bond permanently (cold welding).",
    "Some planets have rings made of dust, ice, and rock particles."
]

animal_facts = [
    "Otters hold hands while they sleep to keep from drifting apart.",
    "Penguins propose to their mates with a pebble.",
    "Sea otters have a pouch in their skin to store their favorite rocks.",
    "A group of kittens is called a 'kindle.'",
    "A baby puffin is called a 'puffling.'",
    "Quokkas, known as the happiest animals on Earth, will often smile for photos.",
    "Elephants can comfort each other by hugging with their trunks.",
    "Sloths can turn their heads almost 360 degrees to look adorable from any angle.",
    "Baby elephants suck their trunks for comfort, just like human babies suck their thumbs.",
    "Hedgehogs curl into tiny, spiky balls when they sleep.",
    "Cows have best friends and get stressed when they’re apart.",
    "Some penguins spend their entire lives with one mate.",
    "Butterflies taste with their feet, making every flower visit a tiny dance.",
    "Koalas sleep up to 20 hours a day and hug trees to cool off.",
    "A group of bunnies is called a 'fluffle.'",
    "Dogs can understand up to 250 words and gestures, making them excellent listeners.",
    "Red pandas use their bushy tails as blankets to keep warm.",
    "Pygmy marmosets, the world’s smallest monkeys, can fit in the palm of your hand.",
    "Manatees are nicknamed 'sea cows' because of their gentle and slow-moving nature.",
    "Baby kangaroos, called joeys, live in their mom’s pouch for several months.",
    "Gentoo penguins can swim up to 22 mph, the fastest of all penguins.",
    "Some frogs can freeze solid in winter and thaw out in spring without harm.",
    "Dolphins have names for each other and recognize themselves in mirrors.",
    "Rabbits perform a happy jump and twist called a 'binky.'",
    "Baby sea turtles instinctively head toward the ocean after hatching.",
    "Octopuses collect shiny objects to decorate their dens.",
    "Alpacas hum to communicate with each other and express happiness.",
    "Seahorses mate for life and hold tails while swimming together.",
    "Baby otters can’t swim, so moms wrap them in kelp to keep them safe.",
    "Cats sleep for about 70% of their lives, often curled up adorably.",
    "Golden retrievers are so gentle they can carry an egg in their mouths without breaking it.",
    "Fennec foxes have huge ears to keep cool and look irresistibly cute.",
    "Meerkats stand up straight to look out for danger, resembling tiny guards.",
    "Owls have soft feathers that allow them to fly silently and cutely.",
    "Pandas spend most of their day eating bamboo and looking cuddly.",
    "A group of flamingos is called a 'flamboyance,' matching their colorful appearance.",
    "Clownfish are born male, but some can turn female if needed.",
    "Chinchillas take dust baths to stay clean and keep their fur fluffy.",
    "Beavers slap their tails on water to warn others of danger.",
    "Squirrels plant thousands of trees every year by forgetting where they buried their nuts.",
    "Baby polar bears are born weighing only about one pound.",
    "When happy, guinea pigs make a cute sound called 'popcorning.'",
    "Some monkeys use leaves as umbrellas during rainstorms.",
    "Hummingbirds weigh less than a penny and can flap their wings 80 times per second.",
    "Axolotls can regrow their limbs, making them real-life water superheroes.",
    "Clownfish form schools with a strict social hierarchy based on size.",
    "Foxes use Earth’s magnetic field to hunt by 'pouncing' on prey.",
    "Mother ducks can talk to their ducklings before they hatch to bond with them.",
    "Snow leopards wrap their tails around themselves to keep warm in cold climates.",
    "A group of otters is called a 'romp' on land and a 'raft' in water.",
    "Starfish can regrow their arms, making them ocean cuties with superpowers.",
    "Baby dolphins are born with a mustache that falls off as they grow.",
    "Koalas have unique fingerprints, just like humans.",
    "Dogs have 'puppy eyes' to better communicate with humans.",
    "A group of parrots is called a 'pandemonium,' fitting their playful nature.",
    "Baby goats, called kids, love to jump and climb on everything.",
    "Caterpillars have up to 4,000 muscles in their tiny bodies.",
    "The noses of dogs are wet to help absorb scent chemicals.",
    "Chickens talk to their unhatched chicks to help them recognize their voices.",
    "Otters have the densest fur of any animal, with up to a million hairs per square inch.",
    "Ducks’ quacks have a unique sound that can echo, despite myths to the contrary.",
    "Pigs are smarter than dogs and can play video games with their snouts.",
    "A group of hedgehogs is called a 'prickle,' matching their spiky look.",
    "Baby giraffes are born with a six-foot drop but stand up within an hour.",
    "Cows can recognize faces and remember them for years.",
    "Pufferfish inflate themselves as a defense mechanism and look adorable doing it.",
    "Chameleons change colors to communicate, not just to blend in.",
    "Narwhals’ long tusks are actually enlarged teeth.",
    "Crows can recognize human faces and remember if someone was kind or mean.",
    "Bees communicate by dancing, performing a 'waggle dance' to show food locations.",
    "A group of ladybugs is called a 'loveliness.'",
    "Dolphins sleep with one eye open to stay alert for predators.",
    "Baby bats, called pups, cling to their mothers as they fly.",
    "Arctic foxes use their fluffy tails as blankets in the snow.",
    "Elephants can recognize themselves in mirrors, a sign of self-awareness.",
    "A group of frogs is called an 'army,' even though they’re quite peaceful.",
    "Penguins toboggan on their bellies to move faster and conserve energy.",
    "Wolves have a unique howl that allows pack members to recognize each other.",
    "The platypus closes its eyes, ears, and nose underwater but looks adorable doing it.",
    "Male penguins gift female penguins rocks to win their affection.",
    "Baby chicks can identify their mother’s voice before they hatch.",
    "Seals can clap their flippers, making them look like they’re applauding.",
    "Parrots can learn to mimic words and phrases from their human companions.",
    "Cats knead with their paws because it reminds them of kittenhood.",
    "Otters juggle small rocks for fun, showing off their playful side.",
    "A group of jellyfish is called a 'smack.'",
    "Mice giggle when tickled, though their laughter is too high-pitched for humans to hear.",
    "The heart of a hummingbird beats over 1,200 times per minute.",
    "Albatrosses mate for life and perform elaborate courtship dances.",
    "Raccoons are excellent problem-solvers and can open complex latches.",
    "Dogs’ noses have unique prints, just like human fingerprints.",
    "Capybaras are so social they make friends with other animals like birds and monkeys."
]

positive_psychology_facts = [
    "Your brain is capable of learning new things throughout your entire life (neuroplasticity).",
    "Kindness boosts serotonin levels, making both the giver and receiver feel happier.",
    "Writing down three things you’re grateful for each day can improve your mental health.",
    "People who smile more often tend to live longer, happier lives.",
    "Listening to your favorite music can reduce stress and increase happiness.",
    "Your brain releases dopamine when you accomplish a goal, making you feel rewarded.",
    "Positive self-talk can improve performance and resilience.",
    "Helping others activates the same parts of the brain as receiving a reward.",
    "Laughter reduces stress and strengthens social bonds.",
    "Your subconscious mind processes thousands of positive thoughts every day.",
    "Practicing mindfulness can improve focus and reduce anxiety.",
    "Gratitude is linked to better sleep, lower stress, and improved well-being.",
    "Your brain can generate new connections and strengthen existing ones every time you learn.",
    "Spending time in nature has been proven to boost mood and creativity.",
    "Making eye contact can create a strong sense of trust and connection.",
    "Your brain loves novelty—trying new things can make you feel more alive.",
    "Visualization can improve performance and help you achieve your goals.",
    "Your brain has the ability to reframe negative situations into positive learning experiences.",
    "Acts of kindness release oxytocin, known as the 'love hormone.'",
    "Your brain is wired to seek and appreciate beauty, which boosts happiness.",
    "Hugs lasting over 20 seconds can significantly reduce stress.",
    "Your brain releases endorphins when you exercise, creating feelings of euphoria.",
    "Optimism is associated with better heart health and longer life expectancy.",
    "Deep breathing exercises can calm your mind and improve focus.",
    "Connecting with loved ones activates areas of the brain linked to joy and safety.",
    "Your body mirrors your emotions, which is why smiling can make you happier.",
    "Sleep enhances memory and strengthens problem-solving skills.",
    "Positive affirmations can rewire your brain for success and confidence.",
    "Learning something new keeps your brain young and healthy.",
    "Acts of generosity can boost happiness levels for both the giver and the receiver.",
    "Your brain lights up with happiness when you accomplish small, meaningful tasks.",
    "Spending time with pets can lower blood pressure and increase happiness.",
    "Laughing with others builds stronger relationships and reduces stress.",
    "Your brain's reward center is activated when you give or receive compliments.",
    "Thinking about happy memories can improve your current mood.",
    "A strong sense of purpose is linked to greater overall happiness.",
    "Practicing gratitude can improve physical and mental health.",
    "The brain can adapt to new routines and habits faster than you think.",
    "Positive emotions enhance creative thinking and problem-solving skills.",
    "Your brain responds to kindness with feelings of warmth and joy.",
    "People who meditate regularly have lower stress levels and improved focus.",
    "Spending time with friends increases oxytocin and boosts your mood.",
    "Smelling pleasant scents like lavender can improve relaxation and happiness.",
    "Writing down your goals increases your chances of achieving them.",
    "Your brain rewards you for completing even small steps toward your goals.",
    "Daydreaming enhances creativity and problem-solving abilities.",
    "Laughing burns calories and releases endorphins, your body’s natural painkillers.",
    "Making someone smile boosts your own mood as well as theirs.",
    "Practicing forgiveness is linked to better mental health and stronger relationships.",
    "Setting and achieving goals increases your self-esteem.",
    "Your brain thrives on positivity and seeks more when you practice it regularly.",
    "Sharing your successes with others amplifies feelings of joy and pride.",
    "Learning a new skill boosts your brainpower and confidence.",
    "Surrounding yourself with positive people improves your own happiness.",
    "Your brain remembers joyful moments better than negative ones.",
    "Spending money on experiences rather than things increases long-term happiness.",
    "Self-care practices, like journaling or meditating, improve mental well-being.",
    "Smiling, even if forced, can trigger feelings of genuine happiness.",
    "Your brain is hardwired to form connections and seek companionship.",
    "Acts of self-kindness improve your mood and boost your resilience.",
    "Positive thoughts can improve physical health by reducing stress hormones.",
    "Thinking about loved ones can instantly boost your mood.",
    "Practicing mindfulness enhances your appreciation for everyday joys.",
    "Your brain rewards acts of curiosity by releasing dopamine.",
    "Expressing gratitude to others deepens bonds and increases happiness.",
    "Your brain loves patterns, which is why practicing rituals can bring comfort.",
    "Celebrating small wins trains your brain to seek more positivity.",
    "Positive relationships improve overall health and life satisfaction.",
    "The brain thrives on love and connection, creating lifelong bonds.",
    "Visualizing success can make you more likely to achieve it.",
    "Your brain responds to praise by releasing dopamine, making you feel good.",
    "People who laugh often are generally healthier and live longer.",
    "Music therapy can boost mood and improve mental health.",
    "Spending time in sunlight boosts serotonin levels and improves happiness.",
    "Dancing reduces stress and promotes feelings of joy.",
    "Your brain thrives when you challenge it with puzzles or problem-solving.",
    "Random acts of kindness can create a ripple effect of positivity.",
    "Reflecting on personal achievements increases self-confidence.",
    "Your brain is designed to adapt and grow, even during challenges.",
    "Positive thinking is linked to lower stress levels and greater resilience.",
    "Sharing happy experiences strengthens relationships and enhances joy.",
    "Your brain is constantly learning and creating new neural pathways.",
    "Cheerful colors in your environment can uplift your mood.",
    "Meditation boosts brain health and enhances focus and clarity.",
    "Connecting with your passions increases motivation and happiness.",
    "Practicing optimism strengthens problem-solving and coping skills.",
    "Loving yourself promotes inner peace and outward confidence.",
    "Your brain craves balance, making rest and relaxation essential for well-being.",
    "Surrounding yourself with nature reduces stress and enhances positivity.",
    "Acts of gratitude improve overall well-being and strengthen relationships.",
    "Your brain rewards acts of bravery with feelings of accomplishment and pride.",
    "Thinking positively about the future increases hope and happiness."
]

all_facts = fun_facts + astronomy_facts + animal_facts + positive_psychology_facts